// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOU__HCTyOe5RlWA0SH66C2YEJamuLgWg',
    appId: '1:1024828460837:web:79782ae81b8e869a8bd4cc',
    messagingSenderId: '1024828460837',
    projectId: 'semester-project-db',
    authDomain: 'semester-project-db.firebaseapp.com',
    storageBucket: 'semester-project-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZzi-kPWeNMLgB16s7k7g4djr2vRO7zw',
    appId: '1:1024828460837:android:030d227dd85359348bd4cc',
    messagingSenderId: '1024828460837',
    projectId: 'semester-project-db',
    storageBucket: 'semester-project-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9471Oe1j0OUqXYW2B3yGcjn5Ntf9-d6I',
    appId: '1:1024828460837:ios:453eff461a9d14798bd4cc',
    messagingSenderId: '1024828460837',
    projectId: 'semester-project-db',
    storageBucket: 'semester-project-db.appspot.com',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9471Oe1j0OUqXYW2B3yGcjn5Ntf9-d6I',
    appId: '1:1024828460837:ios:4f4ef82b6656a39d8bd4cc',
    messagingSenderId: '1024828460837',
    projectId: 'semester-project-db',
    storageBucket: 'semester-project-db.appspot.com',
    iosBundleId: 'com.example.studentManagement.RunnerTests',
  );
}
